export type AppLanguage = "pt" | "en";

export const APP_LANGUAGE_KEY = "arquivo-de-herois:idioma:v1";
export const LEGACY_LANGUAGE_KEY = "mm4e-terminology-language:v1";

const englishUi: Record<string, string> = {
  "Abrir menu": "Open menu",
  "Fechar menu": "Close menu",
  "Tema": "Theme",
  "Tema: sistema": "Theme: system",
  "Tema: claro": "Theme: light",
  "Tema: escuro": "Theme: dark",
  "Alternar entre tema do sistema, claro e escuro": "Switch between system, light, and dark themes",
  "Referências": "References",
  "Importar": "Import",
  "Instalar app": "Install app",
  "Nova ficha": "New sheet",
  "Criação de personagens": "Character creation",
  "Suas fichas": "Your sheets",
  "Crie, confira e compartilhe personagens com cálculos automáticos e liberdade para regras da campanha.":
    "Create, review, and share characters with automatic calculations and room for campaign rules.",
  "ficha": "sheet",
  "fichas": "sheets",
  "Fichas anteriores": "Previous sheets",
  "Próximas fichas": "Next sheets",
  "Buscar por nome, identidade ou nível…": "Search by name, identity, or level…",
  "Limpar busca": "Clear search",
  "Mais recentes": "Most recent",
  "Nome A–Z": "Name A–Z",
  "Maior NP": "Highest PL",
  "Nenhuma ficha encontrada": "No sheets found",
  "Ajuste a busca ou crie uma nova ficha.": "Change the search or create a new sheet.",
  "Editar": "Edit",
  "Visualizar": "View",
  "Compartilhar": "Share",
  "Mais ações": "More actions",
  "Salvar agora": "Save now",
  "Exportar JSON": "Export JSON",
  "Exportar TXT": "Export TXT",
  "Imprimir / PDF": "Print / PDF",
  "Excluir ficha": "Delete sheet",
  "O link desta ficha é permanente.": "This sheet link is permanent.",
  "Sincronizado": "Synced",
  "Alterações pendentes": "Unsaved changes",
  "Salvando…": "Saving…",
  "Salvo": "Saved",
  "Salvo neste dispositivo": "Saved on this device",
  "Erro ao salvar": "Save error",
  "Visualização com auditoria": "View with audit",
  "Visualização limpa": "Clean view",
  "Preparando a ficha…": "Preparing the sheet…",
  "Importação universal": "Universal import",
  "Trazer uma ficha": "Import a sheet",
  "Use um arquivo JSON ou TXT do Arquivo de Heróis, cole os dados exportados ou informe qualquer link permanente de ficha.":
    "Use an Arquivo de Heróis JSON or TXT file, paste exported data, or enter any permanent sheet link.",
  "Arraste o arquivo para cá": "Drop the file here",
  "Arquivos JSON ou TXT": "JSON or TXT files",
  "Escolher arquivo": "Choose file",
  "ou cole abaixo": "or paste below",
  "Link ou dados da ficha": "Sheet link or data",
  "https://…/share/… ou o conteúdo exportado": "https://…/share/… or exported content",
  "Cancelar": "Cancel",
  "Importando…": "Importing…",
  "Salvar como nova ficha": "Save as a new sheet",
  "Fechar importação": "Close import",
  "Tipo de construção": "Build type",
  "Personagem do Jogador": "Player Character",
  "NPC": "NPC",
  "Nome do personagem": "Character name",
  "Identidade civil": "Civilian identity",
  "Codinome": "Codename",
  "Jogador": "Player",
  "Campanha": "Campaign",
  "Arquétipo": "Archetype",
  "Nível de Poder": "Power Level",
  "Orçamento de PP": "PP budget",
  "Orçamento personalizado": "Custom budget",
  "Cor de identificação": "Identification color",
  "Conceito": "Concept",
  "Origem": "Origin",
  "Aparência": "Appearance",
  "Personalidade e motivação": "Personality and motivation",
  "Motivações comuns": "Common motivations",
  "Motivações e complicações": "Motivations and complications",
  "Escolher motivação ou complicação": "Choose a motivation or complication",
  "Adicionar complicação": "Add complication",
  "Nenhuma complicação registrada.": "No complications recorded.",
  "Nome": "Name",
  "Tipo": "Type",
  "Descrição": "Description",
  "Outro": "Other",
  "Escolher motivação": "Choose a motivation",
  "Detalhar motivação": "Describe the motivation",
  "Completar identidade": "Complete identity",
  "Corrigir agora": "Fix now",
  "Assistente de criação": "Creation assistant",
  "Modo assistido": "Guided mode",
  "Modo livre": "Free mode",
  "Assistido": "Guided",
  "Livre": "Free",
  "Pesquisar no catálogo": "Search the catalog",
  "Pesquisar em português ou inglês…": "Search in Portuguese or English…",
  "Idioma do site": "Site language",
  "Filtrar por categoria": "Filter by category",
  "Todas": "All",
  "resultado": "result",
  "resultados": "results",
  "Adicionar": "Add",
  "Nenhuma opção encontrada": "No options found",
  "Limpe o filtro ou use a entrada personalizada da seção.":
    "Clear the filter or use the section's custom entry.",
  "BIBLIOTECA DE CRIAÇÃO": "CREATION LIBRARY",
  "Regras, opções e escalas": "Rules, options, and scales",
  "Consulte regras, compare valores e resolva cálculos sem sobrecarregar a ficha.":
    "Review rules, compare values, and resolve calculations without cluttering the sheet.",
  "Pesquisar nas Referências": "Search References",
  "Pesquisar regra, opção, termo em PT ou EN…": "Search a rule, option, or term in PT or EN…",
  "Conteúdo das Referências": "Reference content",
  "Regras": "Rules",
  "Catálogo": "Catalog",
  "Atributos": "Abilities",
  "Perícias": "Skills",
  "Efeitos": "Effects",
  "Medidas": "Measurements",
  "Ficha limpa": "Clean sheet",
  "Com auditoria": "With audit",
  "Ficha compartilhada · link permanente": "Shared sheet · permanent link",
  "Consulte, imprima, exporte ou salve uma cópia editável no seu arquivo.":
    "Review, print, export, or save an editable copy to your archive.",
  "Salvar uma cópia": "Save a copy",
  "Link copiado": "Link copied",
  "Baixar ficha em JSON": "Download sheet as JSON",
  "Baixar ficha em TXT": "Download sheet as TXT",
  "Fechar": "Close",
  "Fechar catálogo": "Close catalog",
  "Fechar Referências": "Close References",
  "Excluir": "Delete",
  "Voltar à biblioteca": "Back to library",
  "Conteúdo da visualização": "View content",
  "Exibe o diagnóstico, os limites e as verificações das regras":
    "Shows diagnostics, limits, and rule checks",
  "Oculta os indicadores de validação e mantém todos os dados da ficha":
    "Hides validation indicators while keeping all sheet data",
  "Entendi": "Got it",
  "Ficha ativa": "Active sheet",
  "Ficha de NPC": "NPC sheet",
  "Ficha compartilhada": "Shared sheet",
  "Ficha do personagem com auditoria": "Character sheet with audit",
  "Ficha limpa do personagem": "Clean character sheet",
  "Personagem sem nome": "Unnamed character",
  "Sem nome": "Unnamed",
  "Conceito ainda não registrado.": "Concept not recorded yet.",
  "Pontos de Poder": "Power Points",
  "Identidade": "Identity",
  "Descritores": "Descriptors",
  "Atributos e defesas": "Abilities and defenses",
  "Defesas": "Defenses",
  "Combate": "Combat",
  "Resistências": "Resistances",
  "Vantagens": "Advantages",
  "Poderes": "Powers",
  "Ataques": "Attacks",
  "Equipamento": "Equipment",
  "Complicações": "Complications",
  "Recursos atuais": "Current resources",
  "Auditoria das regras": "Rules audit",
  "Contabilidade calculada": "Calculated accounting",
  "Notas": "Notes",
  "Força": "Strength",
  "Vigor": "Stamina",
  "Agilidade": "Agility",
  "Intelecto": "Intellect",
  "Consciência": "Awareness",
  "Presença": "Presence",
  "Ataque": "Attack",
  "Ataque corpo a corpo": "Close attack",
  "Ataque à distância": "Ranged attack",
  "Defesa": "Defense",
  "Defesa corpo a corpo": "Close defense",
  "Defesa à distância": "Ranged defense",
  "Iniciativa": "Initiative",
  "Esquiva": "Dodge",
  "Fortitude": "Fortitude",
  "Robustez": "Toughness",
  "Vontade": "Will",
  "Graduação": "Rank",
  "Custo": "Cost",
  "Ação": "Action",
  "Alcance": "Range",
  "Duração": "Duration",
  "Resistência": "Resistance",
  "Extras": "Extras",
  "Falhas": "Flaws",
  "Recursos": "Features",
  "Desvantagens": "Drawbacks",
  "Vínculos": "Links",
  "Total gasto": "Total spent",
  "Atualizando a ficha…": "Updating sheet…",
  "Selecione uma ficha para ver seu diagnóstico.":
    "Select a sheet to see its diagnostics.",
  "Ficha selecionada": "Selected sheet",
  "Limites de NP": "PL limits",
  "Nível de Poder atual": "Current Power Level",
  "Progresso de pontos": "Point progress",
  "Pontos gastos": "Points spent",
  "Editar ficha": "Edit sheet",
  "Editando a ficha": "Editing sheet",
  "Identidade reservada": "Private identity",
  "Link ativo": "Active link",
  "Tudo certo": "All clear",
  "Revisar": "Review",
  "Atualizado": "Updated",
  "Retrato do personagem": "Character portrait",
  "PNG, JPG, WEBP ou GIF · máximo de 5 MB":
    "PNG, JPG, WEBP, or GIF · 5 MB maximum",
  "Atributos de combate": "Combat abilities",
  "Especialização": "Specialization",
  "Somente treinada": "Trained only",
  "Nenhuma perícia graduada.": "No ranked skills.",
  "Nenhuma vantagem registrada.": "No advantages recorded.",
  "Nenhum poder registrado.": "No powers recorded.",
  "Nenhum ataque registrado.": "No attacks recorded.",
  "Nenhum equipamento registrado.": "No equipment recorded.",
  "Adicionar ataque": "Add attack",
  "Adicionar equipamento": "Add equipment",
  "Adicionar vantagem": "Add advantage",
  "Adicionar poder / configuração": "Add power / configuration",
  "Condições atuais": "Current conditions",
  "Pesquisar condição": "Search condition",
  "Custos, limites e decisões": "Costs, limits, and decisions",
  "Seções da ficha": "Sheet sections",
  "Quem é este personagem?": "Who is this character?",
  "Conceito, campanha e parâmetros que controlam todos os cálculos.":
    "Concept, campaign, and parameters that control every calculation.",
  "Atributos e valores derivados": "Abilities and derived values",
  "Alterar um atributo recalcula imediatamente as perícias, a iniciativa e as resistências associadas.":
    "Changing an ability immediately recalculates its related skills, initiative, and resistances.",
  "Perícias e especializações": "Skills and specializations",
  "O modificador usa atributo + graduações + especialização + outros bônus.":
    "The modifier uses ability + ranks + specialization + other bonuses.",
  "Vantagens e recursos": "Advantages and resources",
  "Cada vantagem ou graduação custa 1 PP. Vantagens heroicas e Equipamento também atualizam seus controles próprios.":
    "Each advantage or rank costs 1 PP. Heroic advantages and Equipment also update their own controls.",
  "Poderes, efeitos e matrizes": "Powers, effects, and arrays",
  "Cada efeito calcula custo-base, modificadores, recursos, desvantagens e vínculos com outros valores da ficha.":
    "Each effect calculates base cost, modifiers, features, drawbacks, and links to other sheet values.",
  "Precisão, efeito e resistência": "Accuracy, effect, and resistance",
  "Bônus, graduação e CD são calculados a partir das fontes registradas na ficha.":
    "Bonus, rank, and DC are calculated from the sources recorded on the sheet.",
  "Equipamento e Pontos de Equipamento": "Equipment and Equipment Points",
  "A vantagem Equipamento custa PP. Os itens usam apenas os PE concedidos por ela, sem cobrança duplicada.":
    "The Equipment advantage costs PP. Items use only the EP it grants, without duplicate charges.",
  "Motivações, responsabilidades, relacionamentos, inimigos e fraquezas.":
    "Motivations, responsibilities, relationships, enemies, and weaknesses.",
  "Estado atual da sessão": "Current session state",
  "Pontos Heroicos": "Hero Points",
  "Histórico e notas": "History and notes",
  "Legenda da auditoria": "Audit legend",
  "As cores têm funções claras. Apenas avisos amarelos aceitam decisão manual; verificações objetivas permanecem protegidas.":
    "Colors have clear roles. Only yellow warnings accept a manual decision; objective checks remain protected.",
  "Nenhum resultado": "No results",
  "Tente outro termo ou limpe a pesquisa.": "Try another term or clear the search.",
  "Regras da ficha": "Sheet rules",
  "Cada tópico informa se o resultado é automático, assistido ou decidido na mesa.":
    "Each topic states whether the result is automatic, guided, or decided at the table.",
  "Opções para criação": "Creation options",
  "Escala de atributos": "Ability scale",
  "Graduação do atributo": "Ability rank",
  "Perícias e testes": "Skills and checks",
  "Modificador total": "Total modifier",
  "Níveis de Poder": "Power Levels",
  "Graduações e medidas": "Ranks and measurements",
  "Tabela métrica de medidas": "Metric measurement table",
  "Criação assistida": "Guided creation",
  "Criação livre": "Free creation",
  "Dependências seguras são mantidas automaticamente.":
    "Safe dependencies are maintained automatically.",
  "Divergências permanecem visíveis, sem bloqueios.":
    "Differences remain visible without blocking your work.",
  "Remover": "Remove",
  "Você está offline.": "You are offline.",
  "A ficha aberta continua disponível; mudanças pendentes serão sincronizadas ao reconectar.":
    "The open sheet remains available; pending changes will sync when you reconnect.",
  "Salve ou sincronize as alterações antes de atualizar o app.":
    "Save or sync your changes before updating the app.",
  "Uma versão mais recente está pronta.": "A newer version is ready.",
  "Atualizar": "Update",
  "Aplicativo instalável": "Installable app",
  "Arquivo de Heróis instalado": "Arquivo de Heróis installed",
  "Adicionar à tela inicial": "Add to Home Screen",
  "O Arquivo de Heróis já pode ser aberto como aplicativo, com os mesmos recursos e dados do site.":
    "Arquivo de Heróis can now open as an app with the same features and site data.",
  "Abra o menu do navegador e escolha Instalar app ou Adicionar à tela inicial. O atalho abre a mesma biblioteca e usa os mesmos dados do site.":
    "Open the browser menu and choose Install app or Add to Home Screen. The shortcut opens the same library and uses the same site data.",
  "Suas fichas continuam sincronizadas. Instalar o aplicativo não cria uma biblioteca separada.":
    "Your sheets stay synchronized. Installing the app does not create a separate library.",
  "Não foi possível abrir esta ficha": "This sheet could not be opened",
  "Abrindo a ficha…": "Opening sheet…",
  "Confira se o endereço foi copiado por inteiro.":
    "Make sure the entire address was copied.",
  "Ir para o Arquivo de Heróis": "Go to Arquivo de Heróis",
  "Abrir arquivo": "Open archive",
  "Enviando…": "Uploading…",
  "Anexar imagem": "Attach image",
  "Codinome / alcunha": "Codename / alias",
  "Personalizado pelo Narrador": "Customized by the Narrator",
  "Sugestões do capítulo de criação": "Creation chapter suggestions",
  "Descritores: origem, fonte, meio e resultado":
    "Descriptors: origin, source, medium, and result",
  "Saldo": "Balance",
  "Narrador / NPC": "Narrator / NPC",
  "Grupo": "Group",
  "Todos os grupos": "All groups",
  "Arquétipos": "Archetypes",
  "Origens": "Origins",
  "Motivações": "Motivations",
  "Outras complicações": "Other complications",
  "Configurações de poder": "Power configurations",
  "Especializações de ataque": "Attack specializations",
  "Resistências sugeridas": "Suggested resistances",
  "Mostrar mais": "Show more",
  "resultado restante": "remaining result",
  "resultados restantes": "remaining results",
  "Calculado": "Calculated",
  "Na mesa": "At the table",
  "Limites de Nível de Poder (NP)": "Power Level (PL) limits",
  "Estrutura de poderes": "Power structure",
  "Integridade dos dados": "Data integrity",
  "Aviso aprovado e retirado das pendências.":
    "Warning approved and removed from pending items.",
  "Aviso reprovado e tratado como erro.":
    "Warning rejected and treated as an error.",
  "Decisão sobre": "Decision for",
  "Manter como aviso amarelo": "Keep as a yellow warning",
  "Manter aviso": "Keep warning",
  "Aprovar e marcar em verde": "Approve and mark green",
  "Aprovar": "Approve",
  "Reprovar e tratar como erro vermelho": "Reject and treat as a red error",
  "Reprovar": "Reject",
  "Auditoria": "Audit",
  "Fonte": "Source",
  "Meio": "Medium",
  "Resultado": "Result",
  "Cálculos validados": "Calculations validated",
  "Nenhum erro objetivo nem aviso aguardando decisão.":
    "No objective errors or warnings awaiting a decision.",
  "Erros objetivos encontrados": "Objective errors found",
  "Abra a auditoria para ver cada regra violada.":
    "Open the audit to see every violated rule.",
  "Avisos aguardando decisão": "Warnings awaiting a decision",
  "Mantenha em amarelo, aprove em verde ou reprove em vermelho.":
    "Keep yellow, approve green, or reject red.",
  "Liberdades do Narrador": "Narrator freedoms",
  "O azul identifica regras mais liberais disponíveis ao Narrador e aos seus NPCs.":
    "Blue identifies more permissive rules available to the Narrator and NPCs.",
};

export function translateUi(value: string, language: AppLanguage): string {
  if (language === "pt") return value;
  const exact = englishUi[value];
  if (exact) return exact;
  const numberedSection = value.match(/^(\d{2}) · (.+)$/);
  if (numberedSection) {
    return `${numberedSection[1]} · ${englishUi[numberedSection[2]] ?? numberedSection[2]}`;
  }
  return value;
}

const englishRuleTerms: Array<[string, string]> = [
  ["Defesa corpo a corpo", "Close defense"],
  ["Defesa à distância", "Ranged defense"],
  ["Ataque corpo a corpo", "Close attack"],
  ["Ataque à distância", "Ranged attack"],
  ["Usos de vantagens heroicas", "Heroic advantage uses"],
  ["Usos heroicos comprados", "Purchased heroic uses"],
  ["Pontos de Equipamento", "Equipment Points"],
  ["Pontos de Poder", "Power Points"],
  ["Motivação do personagem", "Character motivation"],
  ["Maior perícia", "Highest skill"],
  ["ataque + efeito", "attack + effect"],
  ["graduação do efeito", "effect rank"],
  ["sem teste", "no check"],
  ["Robustez", "Toughness"],
  ["Esquiva", "Dodge"],
  ["Vontade", "Will"],
  ["Fortitude", "Fortitude"],
  ["Iniciativa", "Initiative"],
  ["Perícia", "Skill"],
  ["Ataque", "Attack"],
  ["Defesa", "Defense"],
  ["Força", "Strength"],
  ["Motivação", "Motivation"],
  ["personagem", "character"],
  ["graduação", "rank"],
  ["limite", "limit"],
  ["usados", "used"],
  ["disponíveis", "available"],
];

export function translateRuleText(
  value: string,
  language: AppLanguage,
): string {
  if (language === "pt") return value;
  const exact = translateUi(value, language);
  if (exact !== value) return exact;
  return englishRuleTerms.reduce(
    (translated, [portuguese, english]) =>
      translated.replaceAll(portuguese, english),
    value,
  );
}

export function buildTypeLabel(
  type: "hero" | "npc",
  language: AppLanguage = "pt",
): string {
  if (type === "npc") return "NPC";
  return language === "en" ? "Player Character" : "Personagem do Jogador";
}

export function languageName(language: AppLanguage): string {
  return language === "pt" ? "Português" : "English";
}
